### ISSUE TITLE
Hptt is not compiling with -Werror

### ISSUE THREAD

**Issue by nicoTolly** [tongsucn/hptt#1]
Hi,

I tried to build your code and it failed to compile with gcc (GCC) 10.2.0 with a lot of warning for unused variables
```
/home/nico/hptt_git/src/hptt/src/kernels/macro_kernel_trans.cc:245:23: error: unused variable ‘offset_out’ [-Werror=unused-variable]
/home/nico/hptt_git/src/hptt/src/kernels/macro_kernel_trans.cc: In instantiation of ‘void hptt::MacroTransScalar<FloatType, UPDATE_OUT>::exec(const FloatType*, FloatType*, hptt::TensorIdx, hptt::TensorIdx) const [with FloatType = __complex__ double; bool UPDATE_OUT = false; hptt::TensorIdx = long unsigned int]’:
```

Removing the -Werror flag from your cmake/cmake/hptt_config.cmake  file makes it compile.
Could you please fix that ?
Thanks
